name: Generate Dump for CodeRabbit

on:
  pull_request:

jobs:
  generate-dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          
          sudo apt install -y \
            gcc-13 g++-13 \
            gcc-13-multilib g++-13-multilib \
            libstdc++-13-dev libstdc++-13-dev:i386 \
            nasm
      
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100


      - name: Build binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Run mkdump
        run: |
          chmod +x ./mkdump
          ./mkdump

      - name: Upload dump directory for CodeRabbit
        uses: actions/upload-artifact@v4
        with:
          name: coderabbit-dump
          path: dmp/
